In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../dataset/IPL.csv", low_memory=False)

In [3]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [4]:
df.shape

(283678, 65)

In [5]:
df.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'next_batter', 'striker_out'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  str
 3   match_type         283678 non-null  str
 4   event_name         283678 non-null  str
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  str
 7   bowling_team       283678 non-null  str
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  str
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  str
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   str
 22  non_striker        283678 non-null  str
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   str
 25  player_out         14106 non-null   str
 26  fielders           10245 non-null   str
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     str
 29  team_reviewed      907 non-null     str
 30  review_decision    907 non-null     str
 31  umpire             907 non-null     str
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  str
 34  match_won_by       283678 non-null  str
 35  win_outcome        278954 non-null  str
 36  toss_winner        283678 non-null  str
 37  toss_decision      283678 non-null  str
 38  venue              283678 non-null  str
 39  city               283678 non-null  str
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  str
 44  gender             283678 non-null  str
 45  team_type          283678 non-null  str
 46  superover_winner   3896 non-null    str
 47  result_type        4724 non-null    str
 48  method             3890 non-null    str
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  str
 52  stage              283678 non-null  str
 53  match_number       283678 non-null  str
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   str
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  str
 63  next_batter        13593 non-null   str
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), str(35)
memory usage: 203.2 MB

In [7]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [8]:
df.shape

(283678, 65)

In [9]:
df.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'next_batter', 'striker_out'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  str
 3   match_type         283678 non-null  str
 4   event_name         283678 non-null  str
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  str
 7   bowling_team       283678 non-null  str
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  str
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  str
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   str
 22  non_striker        283678 non-null  str
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   str
 25  player_out         14106 non-null   str
 26  fielders           10245 non-null   str
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     str
 29  team_reviewed      907 non-null     str
 30  review_decision    907 non-null     str
 31  umpire             907 non-null     str
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  str
 34  match_won_by       283678 non-null  str
 35  win_outcome        278954 non-null  str
 36  toss_winner        283678 non-null  str
 37  toss_decision      283678 non-null  str
 38  venue              283678 non-null  str
 39  city               283678 non-null  str
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  str
 44  gender             283678 non-null  str
 45  team_type          283678 non-null  str
 46  superover_winner   3896 non-null    str
 47  result_type        4724 non-null    str
 48  method             3890 non-null    str
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  str
 52  stage              283678 non-null  str
 53  match_number       283678 non-null  str
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   str
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  str
 63  next_batter        13593 non-null   str
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), str(35)
memory usage: 203.2 MB

In [11]:
df.shape

(283678, 65)

In [12]:
df.isnull().sum()

Unnamed: 0               0
match_id                 0
date                     0
match_type               0
event_name               0
                     ...
batter_balls             0
bowler_wicket            0
batting_partners         0
next_batter         270085
striker_out              0
Length: 65, dtype: int64